version: '3.1'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - "5432:5432"

  api:
    build: .
    command: npm start
    volumes:
      - .:/app
    ports:
      - "5000:4000"
    depends_on:
      - db

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
